apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfiwuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hfiwuel
  template:
    metadata:
      labels:
        app: hfiwuel
    spec:
      containers:
      - image: okteto.dev/hfiwuel:latest
        name: hfiwuel
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4e659d1f-7060-42b5-8a4a-2801fe37ba88"
        - name: Vless_Path
          value: "/Judgcfiu743g"
        - name: Vmess_UUID
          value: "3cab396e-f66a-40e5-a888-7fec0e6a8368"
        - name: Vmess_Path
          value: "/kifeuyrg98"
        - name: Share_Path
          value: "/v2link"
